### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by hardware** [robgraeber/heroku-buildpack-nodejs-bower-gulp#1]
Hi,

I have a bug with gulp-minify-css, I got this error :

```
Error: Cannot find module 'gulp-minify-css'
```

Here my package.json :

```
{
  "name": "mondedie-chat",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "async": "^1.4.2",
    "bluebird": "^2.10.1",
    "body-parser": "~1.13.2",
    "compression": "^1.5.2",
    "connect-redis": "^2.5.1",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "dotenv": "^1.2.0",
    "emojione": "^1.5.0",
    "express": "~4.13.1",
    "express-debug": "^1.1.1",
    "express-session": "^1.11.3",
    "express-validator": "^2.17.1",
    "highlight.js": "^8.8.0",
    "jade": "~1.11.0",
    "marked": "^0.3.5",
    "moment": "^2.10.6",
    "moment-timezone": "^0.4.0",
    "morgan": "~1.6.1",
    "ms": "^0.7.1",
    "redis": "^1.0.0",
    "request": "^2.61.0",
    "serve-favicon": "~2.3.0",
    "serve-static": "^1.10.0",
    "socket.io": "^1.3.6",
    "socket.io-express-session": "^0.1.2"
  },
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-bower": "0.0.10",
    "gulp-concat": "^2.6.0",
    "gulp-filter": "^3.0.1",
    "gulp-jshint": "^1.11.2",
    "gulp-minify-css": "^1.2.1",
    "gulp-sass": "^2.0.4",
    "gulp-size": "^2.0.0",
    "gulp-uglify": "^1.4.1",
    "jshint-stylish": "^2.0.1"
  },
  "engines": {
    "node": "0.12.x"
  }
}

```

Build log :

```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Node.js/Bower/Gulp app detected
remote: -----> Requested node range:  0.12.x
remote: -----> Resolved node version: 0.12.7
remote: -----> Downloading and installing node
remote: -----> Downloading and installing npm
remote: -----> Installing nasm from source
remote: -----> Restoring node_modules directory from cache
remote: -----> Pruning cached dependencies not specified in package.json
remote: -----> Found bower.json - Updating bower locally
remote:        mondedie-chat@0.0.0 /tmp/build_cc6480202e8ba831abbb424e983d9b81
remote:        └── bower@1.6.3  extraneous
remote:        
remote: -----> Exporting config vars to environment
remote: -----> Installing npm dependencies
remote: -----> Installing bower dependencies
remote:        bower bootstrap#v4.0.0-alpha       not-cached git://github.com/twbs/bootstrap.git#v4.0.0-alpha
remote:        bower bootstrap#v4.0.0-alpha          resolve git://github.com/twbs/bootstrap.git#v4.0.0-alpha
remote:        bower mithril#~0.2.0               not-cached git://github.com/lhorie/mithril.git#~0.2.0
remote:        bower mithril#~0.2.0                  resolve git://github.com/lhorie/mithril.git#~0.2.0
remote:        bower visibilityjs#~1.2.1          not-cached git://github.com/ai/visibility.js.git#~1.2.1
remote:        bower visibilityjs#~1.2.1             resolve git://github.com/ai/visibility.js.git#~1.2.1
remote:        bower HTML5-Desktop-Notifications#*       not-cached git://github.com/ttsvetko/HTML5-Desktop-Notifications.git#*
remote:        bower HTML5-Desktop-Notifications#*          resolve git://github.com/ttsvetko/HTML5-Desktop-Notifications.git#*
remote:        bower HTML5-Desktop-Notifications#*         checkout master
remote:        bower mithril#~0.2.0                        download https://github.com/lhorie/mithril/archive/v0.2.0.tar.gz
remote:        bower visibilityjs#~1.2.1                   download https://github.com/ai/visibility.js/archive/1.2.1.tar.gz
remote:        bower bootstrap#v4.0.0-alpha                download https://github.com/twbs/bootstrap/archive/v4.0.0-alpha.tar.gz
remote:        bower visibilityjs#~1.2.1                    extract archive.tar.gz
remote:        bower HTML5-Desktop-Notifications#*         resolved git://github.com/ttsvetko/HTML5-Desktop-Notifications.git#1ad38f3041
remote:        bower visibilityjs#~1.2.1                   resolved git://github.com/ai/visibility.js.git#1.2.1
remote:        bower bootstrap#v4.0.0-alpha                 extract archive.tar.gz
remote:        bower mithril#~0.2.0                         extract archive.tar.gz
remote:        bower bootstrap#v4.0.0-alpha                resolved git://github.com/twbs/bootstrap.git#4.0.0-alpha
remote:        bower jquery#1.9.1 - 2                    not-cached git://github.com/jquery/jquery.git#1.9.1 - 2
remote:        bower jquery#1.9.1 - 2                       resolve git://github.com/jquery/jquery.git#1.9.1 - 2
remote:        bower jquery#1.9.1 - 2                      download https://github.com/jquery/jquery/archive/2.1.4.tar.gz
remote:        bower jquery#1.9.1 - 2                       extract archive.tar.gz
remote:        bower jquery#1.9.1 - 2                      resolved git://github.com/jquery/jquery.git#2.1.4
remote:        bower mithril#~0.2.0                        resolved git://github.com/lhorie/mithril.git#0.2.0
remote:        bower HTML5-Desktop-Notifications#*          install HTML5-Desktop-Notifications#1ad38f3041
remote:        bower visibilityjs#~1.2.1                    install visibilityjs#1.2.1
remote:        bower bootstrap#v4.0.0-alpha                 install bootstrap#4.0.0-alpha
remote:        bower jquery#1.9.1 - 2                       install jquery#2.1.4
remote:        bower mithril#~0.2.0                         install mithril#0.2.0
remote:        
remote:        HTML5-Desktop-Notifications#1ad38f3041 public/bower/HTML5-Desktop-Notifications
remote:        
remote:        visibilityjs#1.2.1 public/bower/visibilityjs
remote:        
remote:        bootstrap#4.0.0-alpha public/bower/bootstrap
remote:        └── jquery#2.1.4
remote:        
remote:        jquery#2.1.4 public/bower/jquery
remote:        
remote:        mithril#0.2.0 public/bower/mithril
remote: -----> Building runtime environment
remote: -----> Exporting config vars to environment
remote: -----> Updating gulp locally
remote:        mondedie-chat@0.0.0 /tmp/build_cc6480202e8ba831abbb424e983d9b81
remote:        ├─┬ body-parser@1.13.3
remote:        │ └─┬ http-errors@1.3.1
remote:        │   └── inherits@2.0.1 
remote:        ├─┬ express@4.13.3
remote:        │ └─┬ send@0.13.0
remote:        │   └─┬ http-errors@1.3.1
remote:        │     └── inherits@2.0.1 
remote:        ├─┬ express-debug@1.1.1
remote:        │ └─┬ jade@0.29.0
remote:        │   └─┬ monocle@0.1.50
remote:        │     └─┬ readdirp@0.2.5
remote:        │       └─┬ minimatch@3.0.0 
remote:        │         └─┬ brace-expansion@1.1.1 
remote:        │           ├── balanced-match@0.2.0 
remote:        │           └── concat-map@0.0.1 
remote:        ├─┬ jade@1.11.0
remote:        │ ├─┬ mkdirp@0.5.1 
remote:        │ │ └── minimist@0.0.8 
remote:        │ └─┬ uglify-js@2.5.0
remote:        │   └─┬ yargs@3.5.4
remote:        │     └── camelcase@1.2.1 
remote:        ├─┬ request@2.65.0
remote:        │ ├─┬ bl@1.0.0
remote:        │ │ └─┬ readable-stream@2.0.2 
remote:        │ │   ├── core-util-is@1.0.1 
remote:        │ │   ├── inherits@2.0.1 
remote:        │ │   ├── isarray@0.0.1 
remote:        │ │   ├── process-nextick-args@1.0.3 
remote:        │ │   ├── string_decoder@0.10.31 
remote:        │ │   └── util-deprecate@1.0.2 
remote:        │ └─┬ har-validator@2.0.2
remote:        │   ├─┬ chalk@1.1.1 
remote:        │   │ ├── ansi-styles@2.1.0 
remote:        │   │ ├── escape-string-regexp@1.0.3 
remote:        │   │ ├─┬ has-ansi@2.0.0 
remote:        │   │ │ └── ansi-regex@2.0.0 
remote:        │   │ ├─┬ strip-ansi@3.0.0 
remote:        │   │ │ └── ansi-regex@2.0.0 
remote:        │   │ └── supports-color@2.0.0 
remote:        │   ├─┬ is-my-json-valid@2.12.2
remote:        │   │ └── xtend@4.0.0 
remote:        │   └─┬ pinkie-promise@1.0.0 
remote:        │     └── pinkie@1.0.0 
remote:        ├─┬ serve-static@1.10.0
remote:        │ └─┬ send@0.13.0
remote:        │   └─┬ http-errors@1.3.1
remote:        │     └── inherits@2.0.1 
remote:        └─┬ socket.io@1.3.7
remote:          ├─┬ engine.io@1.5.4
remote:          │ └─┬ engine.io-parser@1.2.2
remote:          │   └─┬ has-binary@0.1.6
remote:          │     └── isarray@0.0.1 
remote:          ├─┬ has-binary-data@0.1.3
remote:          │ └── isarray@0.0.1 
remote:          ├─┬ socket.io-adapter@0.3.1
remote:          │ └─┬ socket.io-parser@2.2.2
remote:          │   └── isarray@0.0.1 
remote:          ├─┬ socket.io-client@1.3.7
remote:          │ └─┬ has-binary@0.1.6
remote:          │   └── isarray@0.0.1 
remote:          └─┬ socket.io-parser@2.2.4
remote:            └── isarray@0.0.1 
remote:        
remote: -----> Found gulpfile, running gulp default task
remote: module.js:338
remote:     throw err;
remote:           ^
remote: Error: Cannot find module 'gulp-minify-css'
remote:     at Function.Module._resolveFilename (module.js:336:15)
remote:     at Function.Module._load (module.js:278:25)
remote:     at Module.require (module.js:365:17)
remote:     at require (module.js:384:17)
remote:     at Object.<anonymous> (/tmp/build_cc6480202e8ba831abbb424e983d9b81/gulpfile.js:2:14)
remote:     at Module._compile (module.js:460:26)
remote:     at Object.Module._extensions..js (module.js:478:10)
remote:     at Module.load (module.js:355:32)
remote:     at Function.Module._load (module.js:310:12)
remote:     at Module.require (module.js:365:17)
remote:     at require (module.js:384:17)
remote: 
remote:  !     Push rejected, failed to compile Node.js/Bower/Gulp app
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to mondedie-chat.
remote: 
To git@heroku.com:mondedie-chat.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:mondedie-chat.git'
```

Any idea ?

**Comment by robgraeber** [comment]
If NODE_ENV=production then npm doesn't install the dev dependencies.

**Comment by robgraeber** [comment]
Hey I changed it so npm always installs dev dependencies, let me know if that works. I figure if you're using this buildpack to run gulp then you probably need dev dependencies.

**Comment by hardware** [comment]
it's work, thank :smile:

**Comment by robgraeber** [comment]
Cool :+1:
